### ISSUE TITLE
Party membership

### ISSUE THREAD

**Issue by tim488** [jolyphil/btmembers#1]
Hi,
we found, that MdBs are not able to switch parties in you implementation.
For example:
Martin Hohmann was in the CDU and switched to the AfD, but shows up in your csv as AfD only.
This is probably because you use the PARTEI_KURZ which is there only once per person. 
Maybe one could use the INS_LANG with INS_ART == Fraktion/Gruppe under WAHLPERIODE>INSTITUTIONEN, but I am not sure.
I hope you can fix this, we weren't expecting that behavior^^ Otherwise, thank you for your work!

**Comment by jolyphil** [comment]
Hi, 
The objective of btmembers is to simplify the XML document provided by the Bundestag in order to facilitate its use. The two main simplifications operated on the original file are the following: 1) only the most recent names of the MdBs are kept and 2) functions occupied by the the MdBs are not reported. 
The reason for 2) is that fitting this information in a tabular dataset would require having a three-level hierarchical structure: function --> parliamentary term --> MdB. 
As you mentioned, membership in a faction is reported in INS_ART. But members can change party in the *middle of their term,* which makes it difficult to fit this variable at the member-term level. 
I'm working on a new version of btmembers that will give users the option to download four separate datasets: biography, names, parliamentary terms, and functions. Users will have the option to combine these datasets using MdBs' ID and term number as merging keys. 
I am planing to release the new version at the end of August. 
You might be interested by this paper in which I introduce btmembers and discuss its current limitations:
https://osf.io/vthnq/

**Comment by jolyphil** [comment]
Hi, 

In version 0.1.0 of btmembers, you now have the option to import the Bundestag data either as (a) four data frames nested into a list (retaining all the information of the original XML file) or (b) as a single, condensed data frame, where units of analysis are member-terms.

If (b), a new column named `fraktion` is added to the data. `fraktion` is a recoded variable and refers to the faction the member spent most time in during a given parliamentary term. 

This should fix the issue you submitted.
